### ISSUE TITLE
how exactly do you add userid to admin table?

### ISSUE THREAD

**Issue by DMT-Psychonaut** [dclipca/eckmar#21] opened 2022-04-25 16:44 UTC
how exactly do you add userid to admin table?

**Comment by charon-iv6** [comment] 2022-05-12 12:41
u can 2 it in 2 ways : 1 - run the "php artisan db:seed" then change the admin user id or just copy ur user id from users table then add it there (u can install phpmyadmin in the /var/www/market/public path so u can access mysql db easier)

**Comment by dclipca** [comment] 2022-05-18 08:43
Closing this as it seems the issue is solved.

**Closed by dclipca** 2022-05-18 08:43 UTC
